global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: service-template-http
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: [api-proxy:8080]
        labels:
          service_name: api-proxy
          service_namespace: service-template
      - targets: [app-service:8080]
        labels:
          service_name: app-service
          service_namespace: service-template
  - job_name: service-template-health
    metrics_path: /healthmetrics
    static_configs:
      - targets: [api-proxy:8080]
        labels:
          service_name: api-proxy
      - targets: [app-service:8080]
        labels:
          service_name: app-service
  - job_name: service-template-node
    static_configs:
      - targets: [node-exporter:9100]
        labels:
          service_name: node-exporter

